[versions]

androidGradlePlugin = "8.3.1"
kotlin = "1.9.22"
ktx = "1.12.0"
appcompat = "1.6.1"
materialVersion = "1.11.0"
constraintlayout = "2.1.4"
material = "1.2.1"
flexbox = "3.0.0"
splashscreen = "1.0.1"
glide = "4.16.0"
ksp = "1.9.22-1.0.17"
retrofit = "2.9.0"
okhttp = "4.11.0"
compose = "1.6.4"
composeActivity = "1.8.2"
composeNavigation = "2.7.7"
composeDestinations = "2.1.0-beta01"
navigation = "2.7.7"
lifecycle = "2.7.0"
room = "2.6.1"
hilt = "2.50"
hiltCompiler = "1.2.0"
coil = "2.5.0"

junit = "4.13.2"
junitExt = "1.1.5"
uiautomator = "2.3.0"
espresso = "3.5.1"
kaspresso = "1.5.3"
allure = "2.4.0"
wiremock = "2.27.2"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout"}
flexbox =  { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
splashscreen =  { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide"}
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-material = { group = "androidx.compose.material3", name = "material3", version.ref = "material" }

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "composeNavigation" }
compose-navigation-destinations-core = { group = "io.github.raamcosta.compose-destinations", name = "core", version.ref = "composeDestinations" }
compose-navigation-destinations-ksp = { group = "io.github.raamcosta.compose-destinations", name = "ksp", version.ref = "composeDestinations" }
fragment-navigation =  { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
ui-navigation =  { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }

lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }

hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltCompiler" }
hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltCompiler" }
hilt-compiler-android = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-ext-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitExt" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
kaspresso = { group = "com.kaspersky.android-components", name = "kaspresso", version.ref = "kaspresso" }
kaspresso-allure = { group = "com.kaspersky.android-components", name = "kaspresso-allure-support", version.ref = "kaspresso" }
kaspresso-compose = { group = "com.kaspersky.android-components", name = "kaspresso-compose-support", version.ref = "kaspresso" }
allure-kotlin-model = { group = "io.qameta.allure", name = "allure-kotlin-model", version.ref = "allure" }
allure-kotlin-commons = { group = "io.qameta.allure", name = "allure-kotlin-commons", version.ref = "allure" }
allure-kotlin-junit4 = { group = "io.qameta.allure", name = "allure-kotlin-junit4", version.ref = "allure" }
allure-kotlin-android = { group = "io.qameta.allure", name = "allure-kotlin-android", version.ref = "allure" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock-standalone", version.ref = "wiremock" }
compose-testing-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }
compose-testing-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
